// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221005160631_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("api.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mildred Prohaska"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tina Hamill"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ken Farrell"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Timmy Conn"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Deborah Turcotte"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Angela Kilback"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hannah Cassin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Krystal Cole"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Betty Erdman"
                        },
                        new
                        {
                            Id = 10,
                            Name = "John Jenkins"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Rachel Schimmel"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Elbert Farrell"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Randal Harber"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Angie MacGyver"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Francis Wuckert"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Sophie Monahan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Lula Cummings"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Mack Toy"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Eleanor Jast"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Stanley Bergstrom"
                        });
                });

            modelBuilder.Entity("api.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Body = "Nostrum qui deleniti recusandae repellendus asperiores.\nDicta voluptatum quos et dicta deserunt aspernatur sint eum.\nInventore porro iste enim aliquam optio aut.\nUt reprehenderit nam vel.\nUt sit id rerum quae porro provident deleniti.\nSuscipit qui ea error modi quibusdam odio est in cupiditate.\nSunt debitis velit quod nesciunt.\nQuia quis omnis.\nId explicabo impedit fugiat tenetur veritatis.\nTenetur ab sed exercitationem dicta dolorem.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 972, DateTimeKind.Local).AddTicks(4607),
                            Title = "Expedita recusandae sint exercitationem."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 8,
                            Body = "Quo fuga doloribus eos ab.\nNam voluptatibus et atque aut deserunt neque.\nBlanditiis minus corrupti et qui enim id a.\nUt quia aperiam alias impedit illum voluptas quia ut.\nInventore veritatis consequatur laborum a expedita veniam nostrum.\nEt rem ipsa.\nDolores iure impedit est corrupti exercitationem a.\nIn possimus pariatur rerum.\nPerferendis unde tenetur neque aut ad distinctio earum odit.\nFacilis sed provident asperiores ducimus reiciendis expedita nisi.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(5948),
                            Title = "Aut hic est rem."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 7,
                            Body = "Dolorem minima repudiandae iure ducimus deleniti nemo sapiente ut eos.\nId suscipit repudiandae sint velit vel libero doloremque.\nEt provident a ullam excepturi modi sint velit.\nSuscipit odit fugit non a asperiores qui.\nAd dolores fuga voluptas nobis.\nReprehenderit aliquid impedit rerum.\nEum aut molestiae ipsa accusamus accusamus recusandae quidem.\nLaborum officiis modi error eveniet.\nHarum aperiam non aut vel sint.\nQuo odit quia voluptate quam vel vel error.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(6842),
                            Title = "Nemo quo eveniet et."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 19,
                            Body = "Velit veritatis dolore veritatis voluptatem ea.\nMaxime in enim inventore et ad sint.\nDolorem et voluptatem dolorem eos.\nQui et laudantium ducimus iste.\nPossimus nam quasi rerum iure.\nDelectus modi aut minima quod.\nNatus consectetur sunt impedit et.\nDoloribus aut et quia quia.\nVoluptatem aliquid odio dolor officia adipisci dolor et totam aut.\nVitae voluptas harum tempore fugit enim nostrum eum.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(7284),
                            Title = "Aut qui quia culpa."
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 11,
                            Body = "Fugit sapiente sed praesentium.\nReprehenderit unde ut ipsum voluptatem eaque.\nRepellendus quidem omnis et consequuntur necessitatibus praesentium ducimus aut vel.\nTempore officiis autem in dolorem.\nId esse sunt quos consequatur voluptatum ut.\nSequi sit impedit adipisci ut sequi enim quidem.\nNon expedita est quae.\nSit et et.\nMinus est dignissimos qui.\nIllum est sapiente iusto et rerum eum omnis.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(7672),
                            Title = "Neque et voluptatem hic."
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            Body = "Aliquam rem modi sapiente eaque quidem voluptatem sint.\nSed optio in quis.\nVoluptas quod perspiciatis modi sunt ex saepe totam in quisquam.\nEst at placeat dolores et non.\nQui ab dolore.\nExcepturi qui ea rerum qui eveniet molestias molestiae.\nQuas distinctio reprehenderit itaque quam alias laborum in.\nAt repellendus saepe quas omnis aliquid repellendus.\nQuam voluptatem quia et aliquam ut maxime.\nTempora vel illum fuga.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(8073),
                            Title = "Perspiciatis fugiat ut officiis."
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 20,
                            Body = "Doloremque laudantium vel beatae veritatis animi tempore et adipisci praesentium.\nAut dolor illo neque aut voluptatum ex odit aut.\nNihil facilis temporibus consectetur.\nAutem est iste vero.\nMaxime cupiditate est voluptatem quia cumque laboriosam dicta quisquam.\nEt eaque veniam aliquid eius harum voluptas praesentium beatae occaecati.\nIpsa et expedita est illum accusantium necessitatibus.\nConsequatur eveniet architecto laboriosam quidem ab atque provident minus voluptas.\nDolores ut eum sequi.\nEum ea odio ut iste accusantium enim.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(8552),
                            Title = "Repellat a ratione reiciendis."
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 10,
                            Body = "Quo quas cum qui non repudiandae inventore iste cumque est.\nId aut doloremque dolorum ut.\nSuscipit expedita quo aperiam tempora blanditiis.\nEt voluptatem dolor qui mollitia alias velit.\nDolorem sed voluptatem suscipit quas.\nInventore rem explicabo et soluta quo eos ut.\nRepellat eligendi in tenetur rerum quae.\nSapiente corrupti ab sunt provident saepe magni voluptatum a cumque.\nHic voluptates error consequatur.\nIn cumque minima amet et.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(9001),
                            Title = "Laboriosam modi nihil expedita."
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 20,
                            Body = "Repellendus saepe sit ab cupiditate ullam aut in sed.\nVelit sequi neque laboriosam dolorum.\nVoluptatibus voluptatum consectetur.\nNecessitatibus doloribus voluptate dolor magnam.\nEos voluptas asperiores earum nemo facilis voluptas.\nUt culpa itaque.\nQuo et doloremque maiores rem repellat maiores perspiciatis.\nNulla repellat vero.\nUt quaerat commodi reiciendis quibusdam corrupti voluptas.\nSint odio omnis culpa deserunt voluptatibus assumenda enim eos.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(9440),
                            Title = "Perspiciatis maxime ducimus est."
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 20,
                            Body = "Exercitationem ut sint voluptate consectetur impedit dolores.\nSit eos eum.\nIure deleniti ab.\nSunt aspernatur at autem numquam voluptatum voluptate.\nSit eius ut aut at tenetur nobis tempora quas quisquam.\nArchitecto minima beatae.\nDicta nihil nihil modi dignissimos non earum vel.\nSunt ducimus hic architecto deleniti ut quia illum dolores.\nReprehenderit aut rem occaecati neque autem blanditiis nesciunt.\nNam velit aut ut aut ducimus voluptas.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 974, DateTimeKind.Local).AddTicks(9858),
                            Title = "Ipsa ipsum sit voluptas."
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 8,
                            Body = "Quo ea rerum.\nConsequatur est placeat provident qui magnam.\nRerum est tempore et ut voluptatem pariatur.\nAb voluptate quo quam sed dolor earum et quo mollitia.\nNatus provident ut ipsam eos quasi harum.\nQuis nulla voluptate alias enim nesciunt reprehenderit fuga voluptatem.\nVoluptatem totam non voluptate reiciendis et libero quia maiores.\nTempora veritatis voluptatibus eaque recusandae et eligendi quae tempore.\nSed perspiciatis ut quas voluptatum qui.\nEa dignissimos quaerat est omnis dolorum at natus.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(275),
                            Title = "Temporibus aliquam sapiente libero."
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Body = "Perferendis dicta et provident nemo et quis et.\nTotam nisi tenetur rerum labore id.\nVoluptatem non fugiat aut.\nCum est ipsa tempore odio.\nVoluptatum consequatur vero ut.\nQuia minus occaecati praesentium in aut.\nMinima enim laboriosam eaque.\nVel animi cum et tenetur molestiae voluptatibus modi quisquam.\nVel laboriosam commodi dolorem vero accusamus.\nSaepe quaerat unde non at harum non porro.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(722),
                            Title = "Consequatur voluptatem iste aliquid."
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Body = "Molestiae quidem non distinctio architecto omnis excepturi cupiditate.\nDebitis voluptatem est rerum aliquid sit aspernatur in sed ullam.\nAutem beatae quos et non ut totam.\nConsequatur consequuntur recusandae praesentium neque cum qui cumque et neque.\nOdit modi quis vel tempore est vitae est vero.\nAb modi recusandae laudantium perferendis voluptas pariatur.\nEt dolores odit exercitationem.\nPorro facere rerum eos est enim ut.\nNam velit suscipit consectetur voluptatem consequatur.\nQui aliquam ducimus minima est commodi possimus ut.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(1115),
                            Title = "Et ab omnis iste."
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 20,
                            Body = "Consequatur doloremque cum vel est expedita fuga.\nPlaceat voluptatum quam a inventore eum vel mollitia.\nOptio voluptatem voluptatem quia consequatur.\nDolorem est magnam a at rerum et praesentium.\nUllam et ullam eum expedita vel impedit ut architecto explicabo.\nAut eos est corporis autem sunt in.\nQui doloremque qui ut iste nisi pariatur consequuntur.\nCumque est repellendus rerum perferendis.\nExpedita eos vitae molestiae earum necessitatibus.\nAut architecto incidunt corporis quo sapiente eaque rerum qui omnis.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(1557),
                            Title = "Asperiores ratione ut animi."
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 11,
                            Body = "Maxime eaque aut aliquam aliquid est ullam nemo.\nA commodi doloribus dolorem nostrum distinctio praesentium.\nPraesentium illo autem consequatur magnam harum necessitatibus dicta velit.\nPerferendis et placeat.\nEst vel qui.\nReprehenderit dolores quidem rerum voluptas.\nEt nobis facere animi quae dolor exercitationem aspernatur vitae.\nUnde quo totam soluta dolores.\nSint dolorem itaque provident quis et.\nHic possimus dolor quo hic enim quia velit illum.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(1990),
                            Title = "Eos aut necessitatibus nulla."
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 15,
                            Body = "Ipsa et qui repudiandae nesciunt.\nPraesentium assumenda nisi est nulla maiores.\nTotam cumque autem atque.\nVel et voluptas et quasi nisi eum possimus aut.\nOdit et mollitia non cupiditate harum consequuntur enim.\nAutem voluptates molestiae quos maiores quo itaque odit.\nOdit minus sed recusandae sed.\nFacere beatae dignissimos quia.\nDeleniti dicta ea nisi qui distinctio voluptatum.\nRepudiandae laudantium officia nisi.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(2371),
                            Title = "Id vitae error debitis."
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 8,
                            Body = "Vero accusantium magni ut unde.\nQuis laborum quia placeat consequatur dolor ducimus amet.\nFacere incidunt quis molestias dicta voluptas quia commodi omnis adipisci.\nOccaecati iure qui pariatur consequatur veniam consequatur voluptas officia.\nMolestiae dolore ut facere.\nSed corrupti est consequatur id perferendis in qui rerum vero.\nOdio ullam unde provident nam quis ipsa qui magni.\nRerum quia maxime vitae consequatur soluta mollitia et quia voluptatibus.\nPossimus sed facilis quo quidem hic blanditiis aut sed.\nDicta asperiores sit nulla et eius inventore atque inventore sed.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(2741),
                            Title = "Dicta aut rerum eum."
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 17,
                            Body = "Qui molestiae sit aut mollitia ipsam officiis architecto nobis sit.\nOptio doloremque quam qui molestiae aut doloribus quibusdam sit natus.\nMaxime laudantium ut ipsam.\nOmnis earum dolores magni esse.\nEt modi non rem ipsam in est quia.\nNeque rerum voluptatem.\nBlanditiis quidem dolorum rerum est.\nIusto fugiat nihil quos sit accusamus voluptatem minima ab explicabo.\nUnde ab atque voluptatem.\nVelit inventore blanditiis optio deserunt.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(3207),
                            Title = "Dolorum maiores incidunt dolorem."
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            Body = "Dolor eos et nesciunt.\nCupiditate eos reiciendis.\nIncidunt qui ut animi ab quia est accusantium reiciendis.\nFugiat fugiat laboriosam vitae odio natus et.\nIn velit fuga ut quam quia qui dicta esse quam.\nBeatae voluptatem repudiandae molestias amet qui totam quo at facilis.\nUllam sit rem praesentium accusantium enim.\nDolor consectetur mollitia fuga est id similique non quaerat.\nVoluptatem officiis delectus nihil corporis.\nUt deserunt et.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(3597),
                            Title = "Non qui architecto vero."
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 7,
                            Body = "Enim molestiae fugit dignissimos et a ullam.\nDolore quidem incidunt suscipit qui velit.\nItaque aut aut sequi.\nVoluptatibus cum assumenda asperiores sunt sunt et odit.\nNobis voluptas numquam placeat quae laboriosam consequatur blanditiis assumenda omnis.\nQuisquam blanditiis porro quasi architecto.\nDucimus dolor maxime iure dolor illo illum nesciunt deserunt.\nNesciunt sed aliquid molestiae explicabo adipisci et.\nAutem perferendis officia ea architecto consequatur atque.\nQuia et ut non.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(3984),
                            Title = "Voluptatem itaque aut pariatur."
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 20,
                            Body = "Ea mollitia molestias repellendus in officia blanditiis maxime.\nSuscipit esse quo quaerat cupiditate voluptatem sequi ad.\nDolorem ipsa aut.\nEt ut recusandae sit amet et.\nPraesentium velit sit et ea fugiat quo illo.\nEt repellat hic.\nQuo ratione autem quis ut.\nQuas consequatur nihil eos dolorem vitae.\nVoluptatibus est ut at vel in iure.\nConsectetur eos qui.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(4382),
                            Title = "Optio et suscipit consequuntur."
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 1,
                            Body = "Odio ipsum sunt omnis nam.\nDolor est voluptatum quod error qui eaque suscipit at.\nIllum pariatur ratione sint sequi ut mollitia natus.\nCupiditate aut qui magnam.\nFacere voluptatem impedit voluptatem quam repellat asperiores consequatur.\nNon commodi sed et distinctio.\nExercitationem voluptatem et perspiciatis voluptatem eaque voluptas eaque qui.\nQuia sunt non.\nQui placeat dolor in temporibus doloribus et.\nNecessitatibus sint at.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(4741),
                            Title = "Vero eligendi amet aspernatur."
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 15,
                            Body = "Voluptas itaque id repudiandae quis quia at recusandae est repudiandae.\nConsequuntur aperiam numquam nihil laudantium.\nDolor sit culpa et.\nLibero culpa amet.\nRerum est deserunt doloremque nemo.\nEt dolorem debitis harum autem est assumenda perspiciatis non.\nQui architecto delectus voluptatibus at cumque.\nVoluptatem voluptas aliquid aperiam similique ratione.\nUt sequi qui odit.\nNeque laboriosam et id blanditiis.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(5118),
                            Title = "Aut provident numquam voluptatem."
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 14,
                            Body = "Voluptate quidem et suscipit reiciendis mollitia et.\nVelit sit quaerat sit.\nA temporibus eos sit nam.\nRerum et nam modi voluptas.\nCupiditate totam molestias quis.\nCommodi quidem mollitia dolorem rerum qui sint vel ut tempore.\nCupiditate optio eos ut aut aliquid est.\nFugiat pariatur tempore molestiae accusantium tempore maxime esse.\nNon qui consequuntur odit repudiandae nihil illum dolorum id aspernatur.\nReprehenderit rerum quia.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(5475),
                            Title = "Et suscipit autem libero."
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 9,
                            Body = "Et sed ipsum.\nVoluptas blanditiis eos eligendi non similique quos velit voluptatibus.\nAnimi dolor perspiciatis.\nLaborum ad quia minima ad magnam.\nAd necessitatibus rerum labore minus molestiae minima omnis.\nVoluptatem explicabo minima nemo voluptatem.\nVeniam quia velit dolorem id vel.\nRepudiandae id est ratione tempore repellendus.\nPossimus qui voluptas et sit similique error dolores.\nDeleniti rerum numquam nihil facilis aut.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(5861),
                            Title = "Eligendi aut qui ut."
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 11,
                            Body = "Sed accusamus odit est dolorem et reiciendis eaque officia qui.\nQuos vitae culpa iusto magnam.\nQuia optio eveniet repellendus libero.\nNon reprehenderit reprehenderit voluptas et explicabo voluptatem et quas quidem.\nIste quo id enim ea nihil officia praesentium.\nSaepe iure quisquam laboriosam et sunt quaerat qui sed.\nMagnam quia sed itaque culpa aliquam.\nAspernatur architecto earum odio cum placeat.\nVel voluptatem est excepturi dicta omnis asperiores enim quia.\nEaque eos libero ab cumque sit quo consequatur temporibus.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(6226),
                            Title = "Et labore dolorem voluptatem."
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 1,
                            Body = "Sit molestiae id sint.\nMolestiae numquam rerum eos sapiente ipsa pariatur.\nIllo ex voluptatum earum aut minus eveniet odio.\nEum qui quod aut et necessitatibus quo.\nRerum alias hic ex quasi quo.\nAutem et autem dolorem dolores aut.\nDistinctio atque sunt.\nEt natus odio laborum quis debitis porro molestiae ut quia.\nQuam asperiores voluptas non reprehenderit architecto eaque eveniet reprehenderit.\nOccaecati dicta ratione beatae ea architecto rerum dolor exercitationem id.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(6668),
                            Title = "Eum dolores voluptatem omnis."
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 6,
                            Body = "Enim porro architecto.\nRerum exercitationem sit sit eum vel et similique.\nPerferendis dolorum qui optio ut voluptates.\nExercitationem provident molestiae et est est.\nTotam sint ea excepturi.\nEst ea aut voluptatem dolorem possimus nisi tempora et.\nOptio reiciendis in autem.\nVeniam sed tempore ipsam molestias.\nNobis id id autem enim et asperiores.\nQuo et reiciendis.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(7103),
                            Title = "Perferendis deleniti blanditiis sequi."
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 18,
                            Body = "Possimus earum et nobis error.\nQuo rerum tempora qui.\nSapiente aliquid nulla sunt alias.\nSunt dolorum et non iste.\nUt quia adipisci et porro aut rerum qui nemo architecto.\nRepudiandae quis aut eos sed in ut nulla quae.\nQuo dicta ea expedita necessitatibus et.\nNihil odio eos est sed.\nMinima molestias consequatur.\nQuia fugiat minima vel reiciendis necessitatibus provident.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(7456),
                            Title = "Et autem inventore quia."
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 19,
                            Body = "Dolorem soluta molestias.\nQuidem sunt fugiat aut dolorem dolore.\nAut et recusandae quae impedit voluptatem animi aliquid.\nEaque omnis perferendis voluptas expedita minus velit eum quisquam.\nQuod nulla minus qui.\nExplicabo optio harum facilis quam sed error exercitationem qui rerum.\nAut tenetur corrupti modi in occaecati odit eius consequatur iure.\nQuod voluptas ut saepe consequatur magnam expedita molestias.\nRatione totam sapiente tenetur perferendis est tenetur recusandae numquam.\nAtque molestiae quia quisquam fuga et.",
                            Timestamp = new DateTime(2022, 10, 5, 17, 6, 30, 975, DateTimeKind.Local).AddTicks(7817),
                            Title = "Porro quia praesentium ut."
                        });
                });

            modelBuilder.Entity("api.Models.BlogPost", b =>
                {
                    b.HasOne("api.Models.Author", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("api.Models.Author", b =>
                {
                    b.Navigation("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
