// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220921122532_fake data")]
    partial class fakedata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tiffany Kerluke"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jeffery Bradtke"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Andrew Schneider"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sara Smith"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Elvira Gerhold"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Alberta Fay"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Krystal Schumm"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sheila Klein"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nettie Prohaska"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Eduardo Hermann"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Debra Jacobs"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kristopher Purdy"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Raquel Homenick"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Arnold Hand"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sherri Schmitt"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Randall White"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Tammy Moore"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lucas Pouros"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ken Lesch"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Erma Von"
                        });
                });

            modelBuilder.Entity("api.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 11,
                            Body = "Possimus ullam quaerat ut optio harum non quo doloribus inventore.\nVoluptatem at facilis dolores aut vitae et quia occaecati.\nAliquam illo molestiae et neque.\nSed asperiores autem voluptas.\nIn odit doloribus necessitatibus nesciunt numquam cumque.\nArchitecto impedit et totam cumque consequuntur iusto minus eum similique.\nSint enim qui sed quas et eum dolorum.\nCorrupti velit voluptas laborum numquam aliquam fuga.\nExpedita dolore vel et sed laboriosam ducimus et.\nOfficia qui quibusdam est esse.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 476, DateTimeKind.Local).AddTicks(2172),
                            Title = "Qui quam mollitia sint."
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 15,
                            Body = "Similique atque facilis.\nMollitia neque et nam et.\nMagnam dignissimos et nobis architecto.\nFacere repellendus enim recusandae.\nRerum ipsum expedita aut dolorem consequatur architecto cum esse rerum.\nMolestiae fuga dolor ipsum id corrupti enim ipsa quo repellendus.\nAccusantium laboriosam veniam exercitationem ipsa laboriosam animi tempore rerum.\nQui ab nobis.\nMaiores modi est aliquid molestiae.\nQui quam commodi occaecati debitis quas ut non voluptatem excepturi.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(4430),
                            Title = "Molestiae qui voluptas sit."
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 6,
                            Body = "Qui non assumenda minus beatae.\nEarum accusamus non sunt dolores vero et voluptatem.\nEligendi velit quibusdam sit est reiciendis.\nEsse sed odio quasi velit et placeat ullam rerum.\nIpsum libero ea et culpa optio voluptates.\nVoluptatum quos doloribus nemo consequatur quae repudiandae alias.\nIn nobis consequatur.\nSed nisi inventore fugit ut exercitationem consequatur sit excepturi.\nTempora est sint.\nHic eos quaerat aut porro necessitatibus fuga magni.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(5422),
                            Title = "Explicabo dolorem aut qui."
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 10,
                            Body = "Voluptate esse quia et.\nConsequatur quidem voluptas ut consequuntur nisi ea.\nVel delectus quis omnis dolorum sunt ea sapiente eos possimus.\nDelectus deleniti ratione ea vero veniam.\nImpedit ut pariatur.\nExplicabo rerum laborum ipsum odit ab fuga excepturi magni voluptas.\nMaiores et neque fugit aut.\nIusto aperiam adipisci enim distinctio quo.\nAperiam nam incidunt totam veritatis sed quidem et.\nBlanditiis accusamus nihil.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(6017),
                            Title = "Est odit non qui."
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            Body = "Fuga optio et dolores ut et quod enim.\nEnim et et et iusto incidunt sapiente.\nOdio qui sequi qui.\nMagni vel recusandae.\nNostrum eligendi eos ipsa ducimus qui vero facilis aperiam.\nRepellat ut omnis.\nQui autem id commodi quidem in aut iusto consectetur consectetur.\nUnde corrupti sit quia et.\nQuo natus fugit hic ab velit voluptatum.\nDolores autem aut ea eius sapiente mollitia soluta eum.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(6563),
                            Title = "Ducimus maiores nemo laboriosam."
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 9,
                            Body = "Maiores vero et libero minus ut et.\nTotam esse ducimus nesciunt voluptatibus facilis ipsa soluta.\nMagni ut et id autem aperiam.\nIncidunt quo et expedita omnis sint quia aut nam doloremque.\nSunt unde quod quod.\nSaepe quia ut maiores assumenda et et aperiam temporibus quod.\nMinima modi tempore molestiae consectetur.\nCupiditate odio sit aperiam qui repudiandae hic non rerum.\nHic sint hic dolores rerum iure.\nEst atque magnam ab sed et aspernatur.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(7028),
                            Title = "Expedita voluptate voluptas quia."
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 17,
                            Body = "Doloribus aut itaque enim voluptatem corporis quisquam.\nNemo non deserunt omnis consequuntur corporis nam occaecati voluptas est.\nNecessitatibus id et dignissimos itaque assumenda quia aut.\nQuia quisquam saepe impedit minima inventore molestias pariatur in soluta.\nSuscipit libero minus.\nAd distinctio ad architecto consequuntur.\nEnim accusantium velit id eaque reiciendis.\nDistinctio alias et cumque exercitationem et soluta officia ipsam aut.\nEt quibusdam illum rerum neque et.\nModi accusamus assumenda ipsum minima.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(7541),
                            Title = "Et sit labore non."
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 10,
                            Body = "Atque odit labore vitae qui consectetur sunt dolor.\nIpsa accusamus illo impedit a dolor.\nConsequatur voluptas et consequatur eos voluptates corporis illum aut.\nCorrupti est alias qui.\nEnim repellendus saepe fugiat est aliquam.\nNumquam et quis voluptatibus sunt aliquam ex illum inventore non.\nPorro labore iste accusamus non fugiat.\nAut nihil ut molestiae cumque pariatur dolor.\nHarum iste ut illum quia consequatur cupiditate sit fugit doloribus.\nAut qui quae laudantium nostrum aspernatur ad tempora quis numquam.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(8119),
                            Title = "Dolore aut corrupti saepe."
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 18,
                            Body = "Fugiat sit temporibus non occaecati aut dolores dolorum quibusdam omnis.\nDicta quos consectetur modi.\nAut provident hic placeat possimus sapiente.\nVoluptas nihil fuga necessitatibus quod omnis fugit aut.\nEos aperiam eligendi alias quia veritatis voluptatum beatae est.\nNam quod eos consectetur minus explicabo.\nVelit natus est aut excepturi numquam accusamus laboriosam laudantium quas.\nRepudiandae reprehenderit voluptas soluta ut atque tempora praesentium et eius.\nQui inventore accusamus.\nSit exercitationem itaque.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(8630),
                            Title = "Odio aliquam veritatis voluptatem."
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            Body = "Iste quis est aliquid qui.\nNam eos iste in dolorem exercitationem culpa voluptatibus velit.\nSapiente ad mollitia est exercitationem quod.\nLabore ducimus aut in in asperiores enim consequatur.\nRerum voluptatum consequuntur.\nFugiat officiis rerum cum omnis.\nVoluptatem deleniti nihil assumenda facere.\nId dicta enim et velit.\nQuasi vel dolorum voluptate ut itaque dolore voluptatem et veniam.\nQuae et aut vero rerum perspiciatis sunt.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(9194),
                            Title = "Ut necessitatibus autem placeat."
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 13,
                            Body = "Provident soluta magni ut.\nVoluptates alias reprehenderit et nam voluptate enim quidem.\nUt cumque et quis iure reiciendis.\nDistinctio fugit est blanditiis autem perspiciatis dolor voluptatibus minima possimus.\nSuscipit et officiis.\nConsequatur voluptatibus animi a.\nDolor quia maiores optio perspiciatis.\nFugit sed recusandae corrupti non.\nEt ad officiis similique atque consequatur officiis commodi.\nVelit facilis voluptates autem reiciendis sed iste placeat saepe.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 478, DateTimeKind.Local).AddTicks(9643),
                            Title = "Et eius ipsa deleniti."
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 10,
                            Body = "Consequuntur hic voluptates deleniti et inventore ab.\nDolorem vel quo sequi alias expedita quia ipsum qui.\nPraesentium assumenda deleniti beatae voluptatem similique aut.\nQuis eaque aperiam et eius aut perspiciatis.\nOdio provident ut reprehenderit recusandae.\nEa at vitae repellat eos quae omnis explicabo similique.\nA fugiat incidunt delectus inventore.\nHarum nisi quis.\nNobis aut facere qui nesciunt doloremque laborum libero numquam.\nEnim laboriosam nam cumque voluptate fuga repellat quia molestiae.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(113),
                            Title = "Est et eligendi minus."
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "Eum sunt culpa minima reprehenderit.\nIste sit veritatis architecto aliquid aspernatur et quo aut iusto.\nDebitis omnis perferendis et ipsum provident natus et ab nemo.\nEnim eos voluptate ut alias exercitationem est blanditiis doloremque iure.\nSaepe quo voluptatem id fuga illo non dolores atque.\nEt quia ea optio quod.\nNumquam eaque voluptatem nulla nisi deserunt facilis impedit.\nLibero vel aspernatur sed.\nEt ea dolores.\nAut corporis ullam.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(610),
                            Title = "Consequatur minima rem facere."
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 12,
                            Body = "Mollitia soluta quod consequatur voluptas voluptatem et natus quam.\nPerspiciatis voluptatum ullam.\nEst ea tenetur.\nMolestiae exercitationem esse libero.\nFuga nisi vel odio.\nEst consequuntur sint itaque temporibus.\nQuae accusantium praesentium nam ut quo in molestias ut.\nTenetur culpa qui incidunt est neque.\nVoluptatem deleniti quaerat voluptate non praesentium fugit distinctio doloremque qui.\nVoluptates nostrum dolores id est.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(1074),
                            Title = "Voluptates quas et omnis."
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 11,
                            Body = "Deserunt quisquam voluptates et eum.\nVoluptas tempora quia soluta atque ipsum magnam praesentium.\nEx sed similique nisi consequatur itaque perferendis.\nMollitia earum eveniet ut saepe.\nNon odit eius.\nAsperiores rerum ut et dolores et dignissimos saepe.\nEt culpa molestiae quia dolore qui sequi dolor ut.\nId minima sit.\nEa ipsam corrupti recusandae quia officiis dolor.\nIn ut et quaerat in asperiores vero fuga itaque ut.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(1538),
                            Title = "Voluptatem qui rerum quis."
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 3,
                            Body = "Et sed id officiis enim sunt et reprehenderit distinctio.\nDolores amet consequatur optio sed.\nFuga dolorum consequatur.\nDolorum maiores similique neque.\nMinima architecto cumque dolorem adipisci.\nLibero qui libero minima.\nDolores nemo nobis.\nEst odit mollitia voluptatem vero tempore.\nEt dolor explicabo excepturi omnis minus aut.\nNam quidem in omnis.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(1961),
                            Title = "Eos in id ipsum."
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            Body = "Totam ipsa laboriosam esse.\nAut ipsam itaque occaecati excepturi sint reprehenderit nemo corporis facilis.\nFugiat sint quasi soluta ea recusandae dolores totam.\nAtque natus facere et totam id aut.\nMagni reprehenderit harum minima.\nRepellendus numquam velit quo non dolores nobis ad sit.\nVoluptates quis sit asperiores sequi.\nQui provident et officiis et excepturi quia error quis.\nEst harum quaerat.\nVoluptates perferendis eum aut.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(2323),
                            Title = "Sit repudiandae tempora laudantium."
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 3,
                            Body = "Dolor laboriosam sequi veniam nulla veniam veniam quod.\nAliquid in vero est ea voluptatem enim necessitatibus.\nOmnis nesciunt quisquam ab sit sequi consequatur saepe.\nQuia eos ullam exercitationem dolorem consequatur ut explicabo laudantium ea.\nPorro consequatur est.\nEt et est.\nQuis reiciendis maiores.\nDelectus at perferendis error repudiandae qui voluptatem repellat sint.\nExercitationem odit aut molestiae illo ut ab blanditiis enim natus.\nAt repudiandae unde eum est ratione aut eum ipsam est.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(2789),
                            Title = "Vero atque error quisquam."
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            Body = "Et ex commodi qui.\nSed assumenda impedit nam voluptatem.\nAt ut alias eum libero molestiae.\nFugit itaque laudantium sit tempora qui non et animi nisi.\nSint aut aspernatur est vitae.\nAut rerum esse omnis minus ratione quo quisquam sed.\nQuaerat voluptas ipsam omnis nisi omnis ab eius.\nEst veritatis consequuntur dolor recusandae maxime sint.\nMolestiae maxime enim eum et blanditiis.\nEst quisquam aut qui.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(3235),
                            Title = "Amet repellat sit dignissimos."
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 8,
                            Body = "Hic est quis error earum nesciunt eum debitis aut reprehenderit.\nAut neque atque aut numquam quisquam velit aut.\nVeniam sit eum sed ab.\nPlaceat expedita quo porro veritatis id odio.\nMaiores ut incidunt eos atque officia odio quas eos.\nBlanditiis facere iste.\nOfficia dolorem et numquam atque quam quidem.\nIure dolorem excepturi voluptatem voluptate quia ipsa eum sit eos.\nUllam et fugiat voluptatibus vero molestiae iure.\nDolor aut voluptatem nam ullam et modi et tempore.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(3732),
                            Title = "Temporibus et praesentium est."
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 14,
                            Body = "Qui et aliquid.\nDolor ut praesentium facere.\nIpsam eius aliquam accusantium facere sit quia nostrum.\nOfficia vero ab.\nEt non aliquam.\nOdit quis minus corrupti.\nExcepturi quasi dignissimos.\nSint molestias omnis non error.\nConsequuntur officia aliquid vitae consequatur.\nEnim corrupti dignissimos iste.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(4270),
                            Title = "Nulla sed voluptatem tempora."
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 1,
                            Body = "Eos voluptates asperiores nesciunt dicta voluptatem et.\nNihil sit qui quas voluptatem.\nProvident rerum accusantium sed et deleniti voluptatem magni.\nDoloribus autem aut nostrum recusandae alias.\nCumque odio id.\nQuis pariatur numquam ea incidunt.\nNisi illo autem.\nLaborum consequatur tempora quod accusantium dolores ea.\nVitae aperiam velit consequatur laudantium consequatur commodi quia minus.\nExercitationem fuga atque qui voluptas.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(4617),
                            Title = "Et quis consequatur excepturi."
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 19,
                            Body = "Illum dolores explicabo possimus qui.\nMaiores expedita unde voluptates et.\nEt ex nihil earum commodi iure quia eaque.\nAutem doloremque omnis.\nEos totam quae ipsam velit nisi laudantium dolor.\nUt eveniet ipsam dolore rerum harum vel.\nSit ea molestiae hic dolorum temporibus inventore.\nDelectus nostrum laudantium officia minima dignissimos odit suscipit aut nobis.\nEarum nisi dolores error ea eveniet suscipit dicta aut fuga.\nPlaceat in expedita.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(5031),
                            Title = "Sit soluta tempore fuga."
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 10,
                            Body = "Soluta maiores ut ducimus illo repellat adipisci.\nDolorem autem voluptatibus labore a.\nOdio quia quae voluptas voluptatem illo quis cumque.\nNisi pariatur perspiciatis necessitatibus non.\nMagnam voluptatum alias non neque tempora a asperiores est.\nVoluptate cumque vitae voluptatem perferendis facilis officiis.\nPariatur eius ad qui repellendus enim maxime incidunt reiciendis.\nConsequatur mollitia excepturi aut voluptatem ducimus sunt ipsam.\nDoloremque autem et atque non ex sit et aliquid sed.\nLabore cumque aut placeat eaque quo.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(5504),
                            Title = "Consectetur et suscipit quibusdam."
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 11,
                            Body = "Magnam tempora doloribus explicabo alias exercitationem iusto quidem eligendi optio.\nNulla alias aliquid minus veritatis repellendus blanditiis eligendi.\nAccusantium sed quos nemo dolorum omnis.\nOmnis sint praesentium.\nNostrum error vero dolore quaerat modi voluptatem.\nVoluptatem repudiandae similique maxime ut.\nMagni placeat est.\nTotam quia ut repellat architecto et quo minus nobis rem.\nTempora rerum porro incidunt.\nConsequatur minima qui.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(5983),
                            Title = "Aut eligendi est totam."
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 3,
                            Body = "Voluptatum praesentium autem hic ut.\nAut eum in qui eos reprehenderit.\nQuos tenetur provident cupiditate ut.\nSunt explicabo doloremque at excepturi totam libero pariatur est.\nQuas fuga quibusdam odit fuga animi dignissimos.\nRepellendus esse maiores incidunt voluptas enim voluptatem sunt soluta architecto.\nAmet similique hic corporis minus eaque ad dignissimos est.\nDeleniti animi quidem in et.\nEum nisi veniam.\nSaepe molestias laborum quod quia aut vero aliquam.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(6427),
                            Title = "Voluptatum voluptas cupiditate consequuntur."
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 15,
                            Body = "Nihil perferendis iste.\nVeritatis et ut sequi quo.\nCorporis illum ut fugiat ipsa labore iusto placeat.\nEa eveniet cum a non dolor.\nSit voluptatem quisquam sit vero eligendi alias in reiciendis temporibus.\nQuas minima numquam quia id tempore ut.\nNemo praesentium voluptatem non atque sequi.\nIure adipisci neque placeat illo ut ratione dolores.\nQuia et qui repellendus laborum vel assumenda vero aliquam est.\nTotam sit vitae nesciunt consequatur doloribus est accusamus rem nesciunt.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(6875),
                            Title = "Deserunt quam repellendus mollitia."
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 17,
                            Body = "Velit tempora minus dolorem ea ratione sit repellat nemo.\nSit dolorem quos est dolorem a omnis tempora sed.\nAut alias quod et.\nAd nam qui excepturi adipisci sapiente animi.\nConsequatur ex et occaecati iste.\nQuia at dicta at sequi aut hic.\nDolor doloribus at deleniti harum voluptatibus.\nOptio velit corrupti.\nMollitia vitae atque id atque aut rerum qui.\nCorrupti suscipit ut iusto sed et aut.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(7374),
                            Title = "Labore eos amet nemo."
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 8,
                            Body = "Ut rerum id distinctio quo voluptas et.\nNemo rerum qui vero.\nQuos voluptas dolore animi quod ut eius et rerum dignissimos.\nQuam ad reiciendis aut maxime tempore.\nEveniet ea aut dolor animi.\nDolorem in natus ut ipsam sit reprehenderit in culpa.\nNeque eaque odit nihil.\nQuia quae consectetur perferendis odio veniam.\nOdio ut excepturi praesentium.\nSoluta et blanditiis maiores enim labore vel omnis.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(7846),
                            Title = "Accusantium ratione officia voluptatem."
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 7,
                            Body = "Illo quo doloremque.\nVeritatis rerum dolore vero in ex repellendus dolorem nesciunt.\nQui a non blanditiis vero unde impedit.\nConsequuntur quaerat pariatur quibusdam.\nEst veritatis laborum autem architecto enim eum incidunt.\nVelit provident qui illum iure dolorem.\nAspernatur sed ratione vitae quibusdam adipisci iure et.\nVoluptatem sequi ut ut quo assumenda ut voluptatem sint.\nQuibusdam sapiente error impedit at est ex.\nUnde cum consequatur eaque.",
                            Timestamp = new DateTime(2022, 9, 21, 13, 25, 31, 479, DateTimeKind.Local).AddTicks(8278),
                            Title = "Impedit magnam sed nihil."
                        });
                });

            modelBuilder.Entity("api.Models.BlogPost", b =>
                {
                    b.HasOne("api.Models.Author", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("api.Models.Author", b =>
                {
                    b.Navigation("BlogPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
